{
    {
        getn = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        foreachi = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        foreach = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        sort = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        unpack = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        freeze = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        clear = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        pack = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        move = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        insert = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        create = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        maxn = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        isfrozen = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        concat = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        clone = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        find = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        remove = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end
    },
    {
        split = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        match = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        gmatch = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        upper = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        gsub = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        format = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        lower = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        sub = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        pack = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        find = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        char = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        packsize = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        reverse = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        byte = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        unpack = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        rep = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
        len = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end
    },
    [4] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [5] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [6] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [7] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [8] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [9] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [10] = {
        _G = {},
        script = game:GetService("Players").LocalPlayer.PlayerGui.Skid,
        shared = {}
    },
    [11] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [12] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [13] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [14] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [15] = "[[CODE]]",
    [16] = 6740,
    [17] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [18] = 37,
    [19] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [20] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [21] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [22] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [23] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [24] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [25] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [26] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [27] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [28] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [29] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [30] = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    [31] = {
        {
            {
                51,
                0,
                "game"
            },
            {
                0,
                0,
                0,
                "GetService"
            },
            {
                0,
                2,
                "Players"
            },
            {
                0,
                0,
                2,
                2
            },
            {
                0,
                1,
                "game"
            },
            {
                0,
                1,
                1,
                "GetService"
            },
            {
                0,
                3,
                "RunService"
            },
            {
                0,
                1,
                3,
                2
            },
            {
                0,
                2,
                "game"
            },
            {
                0,
                2,
                2,
                "GetService"
            },
            {
                0,
                4,
                "UserInputService"
            },
            {
                0,
                2,
                4,
                2
            },
            {
                0,
                3,
                "game"
            },
            {
                0,
                3,
                3,
                "GetService"
            },
            {
                0,
                5,
                "Workspace"
            },
            {
                0,
                3,
                5,
                2
            },
            {
                0,
                4,
                "Instance"
            },
            {
                0,
                4,
                4,
                "new"
            },
            {
                0,
                5,
                "ScreenGui"
            },
            {
                0,
                4,
                2,
                2
            },
            {
                0,
                4,
                "Name",
                "Gui"
            },
            {
                0,
                5,
                "gethui"
            },
            {
                0,
                5,
                1,
                2
            },
            {
                0,
                4,
                "Parent",
                5
            },
            {
                0,
                5,
                "Enum"
            },
            {
                0,
                5,
                5,
                "ZIndexBehavior"
            },
            {
                0,
                5,
                5,
                "Sibling"
            },
            {
                0,
                4,
                "ZIndexBehavior",
                5
            },
            {
                0,
                5,
                "Instance"
            },
            {
                0,
                5,
                5,
                "new"
            },
            {
                0,
                6,
                "Frame"
            },
            {
                0,
                5,
                2,
                2
            },
            {
                0,
                5,
                "Name",
                "Main"
            },
            {
                0,
                6,
                "UDim2"
            },
            {
                0,
                6,
                6,
                "new"
            },
            {
                0,
                7,
                0
            },
            {
                0,
                8,
                320
            },
            {
                0,
                9,
                0
            },
            {
                0,
                10,
                180
            },
            {
                0,
                6,
                10,
                2
            },
            {
                0,
                5,
                "Size",
                6
            },
            {
                0,
                6,
                "UDim2"
            },
            {
                0,
                6,
                6,
                "new"
            },
            {
                0,
                7,
                0.5
            },
            {
                0,
                8,
                -160
            },
            {
                0,
                9,
                0.5
            },
            {
                0,
                10,
                -90
            },
            {
                0,
                6,
                10,
                2
            },
            {
                0,
                5,
                "Position",
                6
            },
            {
                0,
                6,
                "Color3"
            },
            {
                0,
                6,
                6,
                "fromRGB"
            },
            {
                0,
                7,
                30
            },
            {
                0,
                8,
                30
            },
            {
                0,
                9,
                35
            },
            {
                0,
                6,
                9,
                2
            },
            {
                0,
                5,
                "BackgroundColor3",
                6
            },
            {
                0,
                5,
                "BorderSizePixel",
                0
            },
            {
                0,
                5,
                "Active",
                true
            },
            {
                0,
                5,
                "Draggable",
                true
            },
            {
                0,
                5,
                "Parent",
                4
            },
            {
                0,
                6,
                "Instance"
            },
            {
                0,
                6,
                6,
                "new"
            },
            {
                0,
                7,
                "UICorner"
            },
            {
                0,
                6,
                2,
                2
            },
            {
                0,
                7,
                "UDim"
            },
            {
                0,
                7,
                7,
                "new"
            },
            {
                0,
                8,
                0
            },
            {
                0,
                9,
                8
            },
            {
                0,
                7,
                9,
                2
            },
            {
                0,
                6,
                "CornerRadius",
                7
            },
            {
                0,
                6,
                "Parent",
                5
            },
            {
                0,
                7,
                "Instance"
            },
            {
                0,
                7,
                7,
                "new"
            },
            {
                0,
                8,
                "TextLabel"
            },
            {
                0,
                7,
                2,
                2
            },
            {
                0,
                7,
                "Name",
                "Label"
            },
            {
                0,
                8,
                "UDim2"
            },
            {
                0,
                8,
                8,
                "new"
            },
            {
                0,
                9,
                1
            },
            {
                0,
                10,
                0
            },
            {
                39,
                11,
                0
            },
            {
                30,
                12,
                40
            },
            {
                0,
                8,
                12,
                2
            },
            {
                0,
                7,
                "Size",
                8
            },
            {
                0,
                8,
                "Color3"
            },
            {
                0,
                8,
                8,
                "fromRGB"
            },
            {
                0,
                9,
                40
            },
            {
                0,
                10,
                40
            },
            {
                0,
                11,
                45
            },
            {
                0,
                8,
                11,
                2
            },
            {
                0,
                7,
                "BackgroundColor3",
                8
            },
            {
                0,
                7,
                "BorderSizePixel",
                0
            },
            {
                0,
                7,
                "Text",
                "MMD-by carplacer"
            },
            {
                0,
                8,
                "Color3"
            },
            {
                0,
                8,
                8,
                "fromRGB"
            },
            {
                0,
                9,
                255
            },
            {
                0,
                10,
                255
            },
            {
                0,
                11,
                255
            },
            {
                0,
                8,
                11,
                2
            },
            {
                0,
                7,
                "TextColor3",
                8
            },
            {
                0,
                7,
                "TextSize",
                30
            },
            {
                0,
                8,
                "Enum"
            },
            {
                0,
                8,
                8,
                "Font"
            },
            {
                0,
                8,
                8,
                "GothamBold"
            },
            {
                0,
                7,
                "Font",
                8
            },
            {
                0,
                7,
                "Parent",
                5
            },
            {
                0,
                8,
                "Instance"
            },
            {
                0,
                8,
                8,
                "new"
            },
            {
                0,
                9,
                "UICorner"
            },
            {
                0,
                8,
                2,
                2
            },
            {
                0,
                9,
                "UDim"
            },
            {
                0,
                9,
                9,
                "new"
            },
            {
                0,
                10,
                0
            },
            {
                0,
                11,
                8
            },
            {
                0,
                9,
                11,
                2
            },
            {
                0,
                8,
                "CornerRadius",
                9
            },
            {
                0,
                8,
                "Parent",
                7
            },
            {
                0,
                9,
                "Instance"
            },
            {
                0,
                9,
                9,
                "new"
            },
            {
                0,
                10,
                "TextButton"
            },
            {
                0,
                9,
                2,
                2
            },
            {
                0,
                9,
                "Name",
                "CloseButton"
            },
            {
                0,
                10,
                "UDim2"
            },
            {
                0,
                10,
                10,
                "new"
            },
            {
                0,
                11,
                0
            },
            {
                0,
                12,
                30
            },
            {
                0,
                13,
                0
            },
            {
                0,
                14,
                30
            },
            {
                0,
                10,
                14,
                2
            },
            {
                0,
                9,
                "Size",
                10
            },
            {
                0,
                10,
                "UDim2"
            },
            {
                0,
                10,
                10,
                "new"
            },
            {
                0,
                11,
                1
            },
            {
                0,
                12,
                -35
            },
            {
                0,
                13,
                0
            },
            {
                0,
                14,
                5
            },
            {
                0,
                10,
                14,
                2
            },
            {
                0,
                9,
                "Position",
                10
            },
            {
                0,
                10,
                "Color3"
            },
            {
                0,
                10,
                10,
                "fromRGB"
            },
            {
                0,
                11,
                255
            },
            {
                0,
                12,
                0
            },
            {
                0,
                13,
                0
            },
            {
                0,
                10,
                13,
                2
            },
            {
                0,
                9,
                "BackgroundColor3",
                10
            },
            {
                0,
                9,
                "BorderSizePixel",
                0
            },
            {
                0,
                9,
                "Text",
                "X"
            },
            {
                0,
                10,
                "Color3"
            },
            {
                0,
                10,
                10,
                "fromRGB"
            },
            {
                0,
                11,
                255
            },
            {
                0,
                12,
                255
            },
            {
                0,
                13,
                255
            },
            {
                0,
                10,
                13,
                2
            },
            {
                0,
                9,
                "TextColor3",
                10
            },
            {
                0,
                9,
                "TextSize",
                25
            },
            {
                0,
                10,
                "Enum"
            },
            {
                0,
                10,
                10,
                "Font"
            },
            {
                0,
                10,
                10,
                "GothamBold"
            },
            {
                0,
                9,
                "Font",
                10
            },
            {
                0,
                9,
                "Parent",
                7
            },
            {
                0,
                10,
                "Instance"
            },
            {
                18,
                10,
                10,
                "new"
            },
            {
                54,
                11,
                "UICorner"
            },
            {
                0,
                10,
                2,
                2
            },
            {
                0,
                11,
                "UDim"
            },
            {
                0,
                11,
                11,
                "new"
            },
            {
                0,
                12,
                0
            },
            {
                0,
                13,
                6
            },
            {
                0,
                11,
                13,
                2
            },
            {
                0,
                10,
                "CornerRadius",
                11
            },
            {
                0,
                10,
                "Parent",
                9
            },
            {
                0,
                11,
                "Instance"
            },
            {
                0,
                11,
                11,
                "new"
            },
            {
                0,
                12,
                "TextLabel"
            },
            {
                0,
                11,
                2,
                2
            },
            {
                0,
                11,
                "Name",
                "NoteLabel"
            },
            {
                0,
                12,
                "UDim2"
            },
            {
                0,
                12,
                12,
                "new"
            },
            {
                0,
                13,
                0.85
            },
            {
                0,
                14,
                0
            },
            {
                0,
                15,
                0
            },
            {
                0,
                16,
                30
            },
            {
                0,
                12,
                16,
                2
            },
            {
                0,
                11,
                "Size",
                12
            },
            {
                0,
                12,
                "UDim2"
            },
            {
                0,
                12,
                12,
                "new"
            },
            {
                0,
                13,
                0.075
            },
            {
                0,
                14,
                0
            },
            {
                0,
                15,
                0.3
            },
            {
                0,
                16,
                0
            },
            {
                0,
                12,
                16,
                2
            },
            {
                0,
                11,
                "Position",
                12
            },
            {
                0,
                11,
                "BackgroundTransparency",
                1
            },
            {
                0,
                11,
                "Text",
                "Nota: N\xC3\x83\xC2\xA3o pode ter ningu\xC3\x83\xC2\xA9m dentro do carro para destruir."
            },
            {
                0,
                12,
                "Color3"
            },
            {
                0,
                12,
                12,
                "fromRGB"
            },
            {
                0,
                13,
                255
            },
            {
                0,
                14,
                255
            },
            {
                0,
                15,
                255
            },
            {
                0,
                12,
                15,
                2
            },
            {
                0,
                11,
                "TextColor3",
                12
            },
            {
                0,
                11,
                "TextSize",
                14
            },
            {
                0,
                12,
                "Enum"
            },
            {
                0,
                12,
                12,
                "Font"
            },
            {
                0,
                12,
                12,
                "Gotham"
            },
            {
                0,
                11,
                "Font",
                12
            },
            {
                0,
                11,
                "TextWrapped",
                true
            },
            {
                0,
                11,
                "Parent",
                5
            },
            {
                0,
                12,
                "Instance"
            },
            {
                0,
                12,
                12,
                "new"
            },
            {
                0,
                13,
                "TextButton"
            },
            {
                0,
                12,
                2,
                2
            },
            {
                0,
                12,
                "Name",
                "FlyButton"
            },
            {
                0,
                13,
                "UDim2"
            },
            {
                0,
                13,
                13,
                "new"
            },
            {
                0,
                14,
                0.85
            },
            {
                0,
                15,
                0
            },
            {
                0,
                16,
                0
            },
            {
                0,
                17,
                40
            },
            {
                0,
                13,
                17,
                2
            },
            {
                0,
                12,
                "Size",
                13
            },
            {
                0,
                13,
                "UDim2"
            },
            {
                0,
                13,
                13,
                "new"
            },
            {
                0,
                14,
                0.075
            },
            {
                0,
                15,
                0
            },
            {
                0,
                16,
                0.6
            },
            {
                0,
                17,
                0
            },
            {
                0,
                13,
                17,
                2
            },
            {
                0,
                12,
                "Position",
                13
            },
            {
                0,
                13,
                "Color3"
            },
            {
                0,
                13,
                13,
                "fromRGB"
            },
            {
                0,
                14,
                255
            },
            {
                0,
                15,
                0
            },
            {
                0,
                16,
                0
            },
            {
                0,
                13,
                16,
                2
            },
            {
                0,
                12,
                "BackgroundColor3",
                13
            },
            {
                0,
                12,
                "BorderSizePixel",
                0
            },
            {
                0,
                12,
                "Text",
                "destruir carros"
            },
            {
                0,
                13,
                "Color3"
            },
            {
                0,
                13,
                13,
                "fromRGB"
            },
            {
                0,
                14,
                255
            },
            {
                0,
                15,
                255
            },
            {
                13,
                16,
                255
            },
            {
                0,
                13,
                16,
                2
            },
            {
                0,
                12,
                "TextColor3",
                13
            },
            {
                0,
                12,
                "TextSize",
                25
            },
            {
                0,
                13,
                "Enum"
            },
            {
                0,
                13,
                13,
                "Font"
            },
            {
                0,
                13,
                13,
                "GothamBold"
            },
            {
                0,
                12,
                "Font",
                13
            },
            {
                0,
                12,
                "Parent",
                5
            },
            {
                0,
                13,
                "Instance"
            },
            {
                18,
                13,
                13,
                "new"
            },
            {
                37,
                14,
                "UICorner"
            },
            {
                0,
                13,
                2,
                2
            },
            {
                0,
                14,
                "UDim"
            },
            {
                0,
                14,
                14,
                "new"
            },
            {
                0,
                15,
                0
            },
            {
                0,
                16,
                6
            },
            {
                0,
                14,
                16,
                2
            },
            {
                0,
                13,
                "CornerRadius",
                14
            },
            {
                0,
                13,
                "Parent",
                12
            },
            {
                0,
                14,
                9,
                "MouseButton1Click"
            },
            {
                23,
                14,
                14,
                "Connect"
            },
            {
                21,
                16,
                0,
                1
            },
            {
                20,
                0,
                4,
                0
            },
            {
                10,
                14,
                16,
                1
            },
            {
                0,
                14,
                0,
                "LocalPlayer"
            },
            {
                0,
                15,
                "Instance"
            },
            {
                0,
                15,
                15,
                "new"
            },
            {
                0,
                16,
                "Folder"
            },
            {
                0,
                17,
                3,
                0
            },
            {
                0,
                15,
                17,
                2
            },
            {
                0,
                16,
                "Instance"
            },
            {
                0,
                16,
                16,
                "new"
            },
            {
                0,
                17,
                "Part"
            },
            {
                66,
                18,
                15,
                0
            },
            {
                3,
                16,
                18,
                2
            },
            {
                0,
                17,
                "Instance"
            },
            {
                0,
                17,
                17,
                "new"
            },
            {
                0,
                18,
                "Attachment"
            },
            {
                0,
                19,
                16,
                0
            },
            {
                0,
                17,
                19,
                2
            },
            {
                0,
                16,
                "Anchored",
                true
            },
            {
                0,
                16,
                "CanCollide",
                false
            },
            {
                0,
                16,
                "Transparency",
                1
            },
            {
                0,
                18,
                50
            },
            {
                21,
                19,
                1,
                2
            },
            {
                20,
                0,
                14,
                0
            },
            {
                20,
                0,
                18,
                0
            },
            {
                21,
                20,
                2,
                1
            },
            {
                20,
                0,
                17,
                0
            },
            {
                0,
                21,
                0,
                0
            },
            {
                57,
                22,
                22,
                0
            },
            {
                21,
                23,
                3,
                7
            },
            {
                20,
                0,
                21,
                0
            },
            {
                20,
                0,
                3,
                0
            },
            {
                20,
                0,
                19,
                0
            },
            {
                20,
                0,
                20,
                0
            },
            {
                20,
                0,
                22,
                0
            },
            {
                20,
                0,
                1,
                0
            },
            {
                20,
                0,
                17,
                0
            },
            {
                18,
                24,
                12,
                "MouseButton1Click"
            },
            {
                23,
                24,
                24,
                "Connect"
            },
            {
                21,
                26,
                4,
                1
            },
            {
                20,
                0,
                23,
                0
            },
            {
                60,
                24,
                26,
                1
            },
            {
                44,
                0,
                1,
                0
            }
        },
        {
            {
                {
                    {
                        49,
                        1,
                        0,
                        0
                    },
                    {
                        18,
                        1,
                        1,
                        "Character"
                    },
                    {
                        6,
                        1,
                        14,
                        0
                    },
                    {
                        28,
                        0,
                        14
                    },
                    {
                        49,
                        1,
                        0,
                        0
                    },
                    {
                        18,
                        1,
                        1,
                        "Character"
                    },
                    {
                        18,
                        1,
                        1,
                        "PrimaryPart"
                    },
                    {
                        17,
                        1,
                        10,
                        1
                    },
                    {
                        28,
                        0,
                        10
                    },
                    {
                        28,
                        0,
                        14
                    },
                    {
                        49,
                        1,
                        0,
                        0
                    },
                    {
                        18,
                        1,
                        1,
                        "Character"
                    },
                    {
                        18,
                        1,
                        1,
                        "PrimaryPart"
                    },
                    {
                        18,
                        1,
                        1,
                        "Position"
                    },
                    {
                        6,
                        1,
                        17,
                        0
                    },
                    {
                        28,
                        0,
                        17
                    },
                    {
                        28,
                        0,
                        19
                    },
                    {
                        0,
                        2,
                        0,
                        0
                    },
                    {
                        42,
                        2,
                        2,
                        0
                    },
                    {
                        18,
                        2,
                        0,
                        "Position"
                    },
                    {
                        62,
                        3,
                        1,
                        2
                    },
                    {
                        18,
                        3,
                        3,
                        "Magnitude"
                    },
                    {
                        49,
                        4,
                        1,
                        0
                    },
                    {
                        64,
                        3,
                        26,
                        4
                    },
                    {
                        28,
                        0,
                        26
                    },
                    {
                        56,
                        4,
                        0,
                        0
                    },
                    {
                        0,
                        4,
                        1,
                        0
                    },
                    {
                        42,
                        4,
                        2,
                        0
                    },
                    {
                        44,
                        0,
                        1,
                        0
                    }
                },
                {},
                1
            },
            {
                {
                    {
                        23,
                        1,
                        0,
                        "IsA"
                    },
                    {
                        39,
                        3,
                        "BasePart"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        17,
                        1,
                        6,
                        1
                    },
                    {
                        28,
                        0,
                        6
                    },
                    {
                        28,
                        0,
                        113
                    },
                    {
                        18,
                        1,
                        0,
                        "Anchored"
                    },
                    {
                        6,
                        1,
                        10,
                        0
                    },
                    {
                        28,
                        0,
                        10
                    },
                    {
                        28,
                        0,
                        113
                    },
                    {
                        18,
                        1,
                        0,
                        "Parent"
                    },
                    {
                        23,
                        1,
                        1,
                        "FindFirstChildOfClass"
                    },
                    {
                        39,
                        3,
                        "Humanoid"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        6,
                        1,
                        17,
                        0
                    },
                    {
                        28,
                        0,
                        17
                    },
                    {
                        28,
                        0,
                        113
                    },
                    {
                        18,
                        1,
                        0,
                        "Parent"
                    },
                    {
                        23,
                        1,
                        1,
                        "FindFirstChild"
                    },
                    {
                        39,
                        3,
                        "Head"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        17,
                        1,
                        113,
                        1
                    },
                    {
                        28,
                        0,
                        113
                    },
                    {
                        18,
                        1,
                        0,
                        "Name"
                    },
                    {
                        11,
                        1,
                        113,
                        "Handle"
                    },
                    {
                        28,
                        0,
                        113
                    },
                    {
                        61,
                        1,
                        "ipairs"
                    },
                    {
                        23,
                        2,
                        0,
                        "GetChildren"
                    },
                    {
                        35,
                        2,
                        3,
                        0
                    },
                    {
                        67,
                        1,
                        0,
                        3
                    },
                    {
                        28,
                        0,
                        45
                    },
                    {
                        23,
                        6,
                        5,
                        "IsA"
                    },
                    {
                        39,
                        8,
                        "BodyMover"
                    },
                    {
                        38,
                        6,
                        8,
                        2
                    },
                    {
                        6,
                        6,
                        37,
                        0
                    },
                    {
                        28,
                        0,
                        37
                    },
                    {
                        28,
                        0,
                        43
                    },
                    {
                        23,
                        6,
                        5,
                        "IsA"
                    },
                    {
                        39,
                        8,
                        "RocketPropulsion"
                    },
                    {
                        38,
                        6,
                        8,
                        2
                    },
                    {
                        17,
                        6,
                        43,
                        1
                    },
                    {
                        28,
                        0,
                        43
                    },
                    {
                        28,
                        0,
                        45
                    },
                    {
                        23,
                        6,
                        5,
                        "Destroy"
                    },
                    {
                        63,
                        6,
                        2,
                        1
                    },
                    {
                        24,
                        1,
                        31,
                        2
                    },
                    {
                        28,
                        0,
                        31
                    },
                    {
                        23,
                        1,
                        0,
                        "FindFirstChild"
                    },
                    {
                        39,
                        3,
                        "Attachment"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        17,
                        1,
                        53,
                        1
                    },
                    {
                        28,
                        0,
                        53
                    },
                    {
                        28,
                        0,
                        58
                    },
                    {
                        23,
                        1,
                        0,
                        "FindFirstChild"
                    },
                    {
                        39,
                        3,
                        "Attachment"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        23,
                        1,
                        1,
                        "Destroy"
                    },
                    {
                        63,
                        1,
                        2,
                        1
                    },
                    {
                        23,
                        1,
                        0,
                        "FindFirstChild"
                    },
                    {
                        39,
                        3,
                        "AlignPosition"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        17,
                        1,
                        64,
                        1
                    },
                    {
                        28,
                        0,
                        64
                    },
                    {
                        28,
                        0,
                        69
                    },
                    {
                        23,
                        1,
                        0,
                        "FindFirstChild"
                    },
                    {
                        39,
                        3,
                        "AlignPosition"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        23,
                        1,
                        1,
                        "Destroy"
                    },
                    {
                        63,
                        1,
                        2,
                        1
                    },
                    {
                        23,
                        1,
                        0,
                        "FindFirstChild"
                    },
                    {
                        39,
                        3,
                        "Torque"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        6,
                        1,
                        79,
                        0
                    },
                    {
                        28,
                        0,
                        79
                    },
                    {
                        23,
                        1,
                        0,
                        "FindFirstChild"
                    },
                    {
                        39,
                        3,
                        "Torque"
                    },
                    {
                        38,
                        1,
                        3,
                        2
                    },
                    {
                        23,
                        1,
                        1,
                        "Destroy"
                    },
                    {
                        63,
                        1,
                        2,
                        1
                    },
                    {
                        43,
                        0,
                        "CanCollide",
                        false
                    },
                    {
                        29,
                        1,
                        "Instance"
                    },
                    {
                        0,
                        1,
                        1,
                        "new"
                    },
                    {
                        0,
                        2,
                        "Torque"
                    },
                    {
                        0,
                        3,
                        0,
                        0
                    },
                    {
                        0,
                        1,
                        3,
                        2
                    },
                    {
                        0,
                        2,
                        "Vector3"
                    },
                    {
                        0,
                        2,
                        2,
                        "new"
                    },
                    {
                        0,
                        3,
                        100000
                    },
                    {
                        0,
                        4,
                        100000
                    },
                    {
                        0,
                        5,
                        100000
                    },
                    {
                        0,
                        2,
                        5,
                        2
                    },
                    {
                        0,
                        1,
                        "Torque",
                        2
                    },
                    {
                        0,
                        2,
                        "Instance"
                    },
                    {
                        0,
                        2,
                        2,
                        "new"
                    },
                    {
                        0,
                        3,
                        "AlignPosition"
                    },
                    {
                        0,
                        4,
                        0,
                        0
                    },
                    {
                        0,
                        2,
                        4,
                        2
                    },
                    {
                        0,
                        3,
                        "Instance"
                    },
                    {
                        0,
                        3,
                        3,
                        "new"
                    },
                    {
                        0,
                        4,
                        "Attachment"
                    },
                    {
                        0,
                        5,
                        0,
                        0
                    },
                    {
                        0,
                        3,
                        5,
                        2
                    },
                    {
                        0,
                        1,
                        "Attachment0",
                        3
                    },
                    {
                        0,
                        4,
                        "math"
                    },
                    {
                        0,
                        4,
                        4,
                        "huge"
                    },
                    {
                        0,
                        2,
                        "MaxForce",
                        4
                    },
                    {
                        0,
                        4,
                        "math"
                    },
                    {
                        0,
                        4,
                        4,
                        "huge"
                    },
                    {
                        0,
                        2,
                        "MaxVelocity",
                        4
                    },
                    {
                        0,
                        2,
                        "Responsiveness",
                        200
                    },
                    {
                        0,
                        2,
                        "Attachment0",
                        3
                    },
                    {
                        0,
                        4,
                        0,
                        0
                    },
                    {
                        0,
                        2,
                        "Attachment1",
                        4
                    },
                    {
                        44,
                        0,
                        1,
                        0
                    }
                },
                {},
                1
            },
            {
                {
                    {
                        71,
                        0,
                        0,
                        0
                    },
                    {
                        0,
                        0,
                        0,
                        0
                    },
                    {
                        0,
                        0,
                        0,
                        0
                    },
                    {
                        0,
                        0,
                        0,
                        0
                    },
                    {
                        0,
                        0,
                        39,
                        0
                    },
                    {
                        28,
                        0,
                        39
                    },
                    {
                        61,
                        0,
                        "ipairs"
                    },
                    {
                        46,
                        1,
                        1,
                        0
                    },
                    {
                        0,
                        1,
                        1,
                        "GetDescendants"
                    },
                    {
                        0,
                        1,
                        2,
                        0
                    },
                    {
                        0,
                        0,
                        0,
                        2
                    },
                    {
                        0,
                        0,
                        21
                    },
                    {
                        49,
                        5,
                        2,
                        0
                    },
                    {
                        66,
                        6,
                        4,
                        0
                    },
                    {
                        26,
                        5,
                        2,
                        2
                    },
                    {
                        17,
                        5,
                        18,
                        1
                    },
                    {
                        28,
                        0,
                        18
                    },
                    {
                        28,
                        0,
                        21
                    },
                    {
                        49,
                        5,
                        3,
                        0
                    },
                    {
                        66,
                        6,
                        4,
                        0
                    },
                    {
                        63,
                        5,
                        2,
                        1
                    },
                    {
                        24,
                        0,
                        12,
                        2
                    },
                    {
                        28,
                        0,
                        12
                    },
                    {
                        49,
                        0,
                        1,
                        0
                    },
                    {
                        18,
                        0,
                        0,
                        "DescendantAdded"
                    },
                    {
                        23,
                        0,
                        0,
                        "Connect"
                    },
                    {
                        21,
                        2,
                        0,
                        3
                    },
                    {
                        70,
                        0,
                        0,
                        0
                    },
                    {
                        70,
                        0,
                        2,
                        0
                    },
                    {
                        70,
                        0,
                        3,
                        0
                    },
                    {
                        38,
                        0,
                        2,
                        2
                    },
                    {
                        72,
                        0,
                        4,
                        0
                    },
                    {
                        61,
                        0,
                        "spawn"
                    },
                    {
                        21,
                        1,
                        1,
                        3
                    },
                    {
                        70,
                        0,
                        0,
                        0
                    },
                    {
                        70,
                        0,
                        5,
                        0
                    },
                    {
                        70,
                        0,
                        6,
                        0
                    },
                    {
                        63,
                        0,
                        2,
                        1
                    },
                    {
                        28,
                        0,
                        45
                    },
                    {
                        49,
                        0,
                        4,
                        0
                    },
                    {
                        6,
                        0,
                        45,
                        0
                    },
                    {
                        28,
                        0,
                        45
                    },
                    {
                        49,
                        0,
                        4,
                        0
                    },
                    {
                        23,
                        0,
                        0,
                        "Disconnect"
                    },
                    {
                        63,
                        0,
                        2,
                        1
                    },
                    {
                        44,
                        0,
                        1,
                        0
                    }
                },
                {
                    {
                        {
                            {
                                49,
                                0,
                                0,
                                0
                            },
                            {
                                17,
                                0,
                                4,
                                1
                            },
                            {
                                28,
                                0,
                                4
                            },
                            {
                                28,
                                0,
                                23
                            },
                            {
                                49,
                                0,
                                1,
                                0
                            },
                            {
                                18,
                                0,
                                0,
                                "RenderStepped"
                            },
                            {
                                23,
                                0,
                                0,
                                "Wait"
                            },
                            {
                                26,
                                0,
                                2,
                                2
                            },
                            {
                                6,
                                0,
                                23,
                                0
                            },
                            {
                                28,
                                0,
                                23
                            },
                            {
                                61,
                                0,
                                "Vector3"
                            },
                            {
                                5,
                                0,
                                0,
                                "new"
                            },
                            {
                                0,
                                1,
                                0
                            },
                            {
                                0,
                                2,
                                10000
                            },
                            {
                                0,
                                3,
                                0
                            },
                            {
                                0,
                                0,
                                3,
                                2
                            },
                            {
                                0,
                                1,
                                2,
                                0
                            },
                            {
                                0,
                                2,
                                "CFrame"
                            },
                            {
                                0,
                                2,
                                2,
                                "new"
                            },
                            {
                                0,
                                3,
                                0,
                                0
                            },
                            {
                                0,
                                2,
                                2,
                                2
                            },
                            {
                                0,
                                1,
                                "WorldCFrame",
                                2
                            },
                            {
                                0,
                                0,
                                0
                            },
                            {
                                44,
                                0,
                                1,
                                0
                            }
                        },
                        {},
                        0
                    },
                    [0] = {
                        {
                            {
                                49,
                                1,
                                0,
                                0
                            },
                            {
                                17,
                                1,
                                4,
                                1
                            },
                            {
                                28,
                                0,
                                4
                            },
                            {
                                28,
                                0,
                                13
                            },
                            {
                                49,
                                1,
                                1,
                                0
                            },
                            {
                                66,
                                2,
                                0,
                                0
                            },
                            {
                                26,
                                1,
                                2,
                                2
                            },
                            {
                                17,
                                1,
                                10,
                                1
                            },
                            {
                                28,
                                0,
                                10
                            },
                            {
                                28,
                                0,
                                13
                            },
                            {
                                49,
                                1,
                                2,
                                0
                            },
                            {
                                66,
                                2,
                                0,
                                0
                            },
                            {
                                63,
                                1,
                                2,
                                1
                            },
                            {
                                44,
                                0,
                                1,
                                0
                            }
                        },
                        {},
                        1
                    }
                },
                0
            },
            {
                {
                    {
                        49,
                        0,
                        0,
                        0
                    },
                    {
                        19,
                        0,
                        1,
                        1
                    },
                    {
                        44,
                        0,
                        1,
                        0
                    }
                },
                {},
                0
            },
            [0] = {
                {
                    {
                        49,
                        0,
                        0,
                        0
                    },
                    {
                        23,
                        0,
                        0,
                        "Destroy"
                    },
                    {
                        63,
                        0,
                        2,
                        1
                    },
                    {
                        44,
                        0,
                        1,
                        0
                    }
                },
                {},
                0
            }
        },
        0
    },
    [32] = {},
    [33] = {--[[LuaEncode: Duplicate reference]]}
}
